/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Array;
import javax.swing.JOptionPane;
import modelo.Pessoa;
import modelo.Usuario;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.text.Element;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import controle.ListaInstituicao;
import controle.ListaProfessores;
import modelo.Instituicao;
import modelo.ModeloTabela;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
public class ConfigProfessor extends javax.swing.JFrame {

 String diretorio = "C:\\Users\\Wellington\\Documents\\FATEC\\Estrutura de Dados\\XMLs Projeto\\listaProfessores.xml"; //Diretorio do XML professores
 String diretorioInstituicao = "C:\\Users\\Wellington\\Documents\\FATEC\\Estrutura de Dados\\XMLs Projeto\\listaInstituicoes.xml";

    
    
Pessoa pessoa = new Pessoa();
Usuario usuario  = new Usuario();
ArrayList professores = new ArrayList();
ListaProfessores lp  = new ListaProfessores();
String capturaNome;
    /**
     * Creates new form ConfigProfessor
     */
    public ConfigProfessor() {
        initComponents();
        listaInstituicoes();
        ListaProfessor frmListaProfessor = new ListaProfessor();
        
        bloqueiaCampos();
        desativaBtnEAS();
    lp.recuperaDados();
        try { //Inicializa os valores do arquivo na tabela
            preecherTabela();
        } catch (IOException ex) {
            Logger.getLogger(ConfigProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelFoto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelCab = new javax.swing.JPanel();
        jTextFieldPesquisar1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxInstituicao = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldRegistro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProfessor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabelVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(834, 900));

        jPanelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelFoto.setPreferredSize(new java.awt.Dimension(120, 156));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/silhueta-universitario-masculino-com-a-tampa_318-61897.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanelFotoLayout = new javax.swing.GroupLayout(jPanelFoto);
        jPanelFoto.setLayout(jPanelFotoLayout);
        jPanelFotoLayout.setHorizontalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFotoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanelFotoLayout.setVerticalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, Short.MAX_VALUE)
        );

        jPanelCab.setBackground(new java.awt.Color(51, 51, 255));
        jPanelCab.setPreferredSize(new java.awt.Dimension(834, 42));

        jTextFieldPesquisar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldPesquisar1.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPesquisar1.setText("Pesquisar");
        jTextFieldPesquisar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPesquisar1MouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novo_projeto/imagens/Apesquisar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCabLayout = new javax.swing.GroupLayout(jPanelCab);
        jPanelCab.setLayout(jPanelCabLayout);
        jPanelCabLayout.setHorizontalGroup(
            jPanelCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jTextFieldPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCabLayout.setVerticalGroup(
            jPanelCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Inserir imagem");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("RG");

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CPF");

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCpfActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Endereço");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Cidade");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Numero");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Data de Nascimento");

        try {
            jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Sexo");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefone");

        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Instituição");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Nº Registro");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Usuario");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Senha");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText(" Professor");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTableProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProfessorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableProfessor);

        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/arrow_left.png"))); // NOI18N
        jLabelVoltar.setText("Voltar");
        jLabelVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jButtonExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar)
                                .addGap(462, 462, 462))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel9)))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelVoltar)
                                .addGap(110, 110, 110)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel17))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
            .addComponent(jPanelCab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelCab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVoltar)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(84, 84, 84)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addGap(2, 2, 2)
                                .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)))
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCpfActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        
        alteraDados(capturaNome);
        desativaBtnEAS();
        bloqueiaCampos();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        String message = "Você tem certeza que deseja excluir este registro?";
        String title = "Excluir registro";
        
        int reply =  JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        
        if(reply == JOptionPane.YES_OPTION)
        {
        excluiDados(jTextFieldNome.getText());
        lp.SalvaArquivoXML();
        try {
            preecherTabela();
        } catch (IOException ex) {
            Logger.getLogger(ConfigProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }//chave da condição IF
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        
         capturaNome = jTextFieldNome.getText();
        desbloqueiaCampos();
        jButtonSalvar.setVisible(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProfessorMouseClicked
        // TODO add your handling code here:
        ativaBtnEAS();

        String nome = "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),0);
        String rg= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),1);
        String cpf= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),2);
        String endereco= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),3);
        String cidade= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),4);
        String numero= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),5);
        String data= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),6);
        String sexo= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),7);
        String telefone= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),8);
        String email= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),9);
        String registro= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),10);
        String instituicao="" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),11);
        String usuario= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),12);
        String senha= "" + jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(),13);
        //String instituicao

        jTextFieldNome.setText(nome);
        jFormattedTextFieldRg.setText(rg);
        jFormattedTextFieldCpf.setText(cpf);
        jTextFieldEndereco.setText(endereco);
        jTextFieldCidade.setText(cidade);
        jTextFieldNumero.setText(numero);
        jFormattedTextFieldData.setText(data);

        jComboBoxSexo.setSelectedItem(sexo);

        jTextFieldTelefone.setText(telefone);
        jTextFieldEmail.setText(email);
        jTextFieldRegistro.setText(registro);
        jComboBoxInstituicao.setSelectedItem(instituicao);
        jTextFieldUsuario.setText(usuario);
        jTextFieldSenha.setText(senha);
        
    }//GEN-LAST:event_jTableProfessorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CadProfessor formCad = new CadProfessor();
        formCad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVoltarMouseClicked
        // TODO add your handling code here:
         CadProfessor formCad = new CadProfessor();
        formCad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelVoltarMouseClicked

    private void jTextFieldPesquisar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPesquisar1MouseClicked
        // TODO add your handling code here:
        
      //jTextFieldPesquisar1.setText(" ");
    }//GEN-LAST:event_jTextFieldPesquisar1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        buscaDados(jTextFieldPesquisar1.getText());
         ativaBtnEAS();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    
    public void bloqueiaCampos()
    {
        
        
        jComboBoxSexo.enable(false);
       jTextFieldNome.enable(false);
       jFormattedTextFieldRg.enable(false);
       jFormattedTextFieldCpf.enable(false);
       jTextFieldEndereco.enable(false);
       jTextFieldCidade.enable(false);
       jTextFieldNumero.enable(false);
       jFormattedTextFieldData.enable(false);
       //pessoa.setDate(jTextFieldDataNascimento.getText());
       //pessoa.setSexo(jTextFieldSexo.getText());
       jTextFieldTelefone.enable(false);
       jTextFieldEmail.enable(false);
       jTextFieldRegistro.enable(false);
       //pessoa.setUsuario(jTextFieldUsuario.getText());
      //pessoa.setSenha(jTextFieldSenha.getText());
      jComboBoxSexo.enable(false);
      jTextFieldUsuario.enable(false);
      jTextFieldSenha.enable(false);
      jComboBoxInstituicao.enable(false);
        
        
    }
    
    
    
    public void desbloqueiaCampos()
    {
        
       jComboBoxSexo.enable(true);
       jTextFieldNome.enable(true);
       jFormattedTextFieldRg.enable(true);
       jFormattedTextFieldCpf.enable(true);
       jTextFieldEndereco.enable(true);
       jTextFieldCidade.enable(true);
       jTextFieldNumero.enable(true);
       jFormattedTextFieldData.enable(true);
       //pessoa.setDate(jTextFieldDataNascimento.getText());
       //pessoa.setSexo(jTextFieldSexo.getText());
       jTextFieldTelefone.enable(true);
       jTextFieldEmail.enable(true);
       jTextFieldRegistro.enable(true);
       //pessoa.setUsuario(jTextFieldUsuario.getText());
      //pessoa.setSenha(jTextFieldSenha.getText());
      jComboBoxSexo.enable(true);
      jTextFieldUsuario.enable(true);
      jTextFieldSenha.enable(true);
      jComboBoxInstituicao.enable(true);                                                                              
        
    }
    
    public void ativaBtnEAS()
    {
        
        jButtonExcluir.setVisible(true);
        jButtonAlterar.setVisible(true);
       // jButtonSalvar.setVisible(true);
        
    }
    
    
    public void desativaBtnEAS()
    {
        
        jButtonExcluir.setVisible(false);
        jButtonAlterar.setVisible(false);
        jButtonSalvar.setVisible(false);
        
    }
    
    
    
    
    
    
    
    
    
    public void buscaDados(String nome)
    {
        
        
        int indice;
     try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("pessoa", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Pessoa> listaProf2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Pessoa pessoa: listaProf2)
              {
                  
               
               
                  if (nome.equals(pessoa.getNome()))
                  {
                      
                        jTextFieldNome.setText(pessoa.getNome());
                         indice = listaProf2.indexOf(pessoa);
                         System.out.println(indice);
                        jFormattedTextFieldRg.setText(pessoa.getRG());
                        //jTextFieldRG.setText(pessoa.getRG());
                        jFormattedTextFieldCpf.setText(pessoa.getCPF()); //CPF formatado
                        //jTextFieldCPF.setText(pessoa.getCPF());
                        jTextFieldEndereco.setText(pessoa.getEnd());
                        jTextFieldCidade.setText(pessoa.getCidade());
                        jTextFieldNumero.setText(pessoa.getNumero());
                        jFormattedTextFieldData.setText(pessoa.getDate());
                        //jTextFieldDataNascimento.setText(pessoa.getDate());
                        jComboBoxSexo.setSelectedItem(pessoa.getSexo());  //(pessoa.getSexo());  //(pessoa.getSexo()); JComboBox
                        jTextFieldTelefone.setText(pessoa.getTelefone());
                        jTextFieldEmail.setText(pessoa.getEmail());
                        jTextFieldRegistro.setText(pessoa.getRegistro());
                        
                        jComboBoxInstituicao.setSelectedItem(pessoa.getInstituicao());
                        
                        jTextFieldUsuario.setText(pessoa.getUsuario());
                        jTextFieldSenha.setText(pessoa.getSenha());
                      
                       
               }
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    public void alteraDados(String nome)
    {
      int indice;  
       try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("pessoa", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Pessoa> listaProf2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Pessoa pessoa: listaProf2)
              {
                  
               
               
                  if (nome.equals(pessoa.getNome()))
                  {
                      
                       
                         indice = listaProf2.indexOf(pessoa);
                         System.out.println(indice);
                         
                        
                         
                           
                    // Passando dados para a a classe pessoa
                pessoa.setNome(jTextFieldNome.getText());
                pessoa.setRG(jFormattedTextFieldRg.getText());
                pessoa.setCPF(jFormattedTextFieldCpf.getText());
                pessoa.setEnd(jTextFieldEndereco.getText());
                pessoa.setCidade(jTextFieldCidade.getText());
                pessoa.setNumero(jTextFieldNumero.getText());
                pessoa.setDate(jFormattedTextFieldData.getText());
                //pessoa.setDate(jTextFieldDataNascimento.getText());
                //pessoa.setSexo(jTextFieldSexo.getText());
                pessoa.setTelefone(jTextFieldTelefone.getText());
                pessoa.setEmail(jTextFieldEmail.getText());
                pessoa.setRegistro(jTextFieldRegistro.getText());
                
                pessoa.setInstituicao((String) jComboBoxInstituicao.getSelectedItem());

                //pessoa.setUsuario(jTextFieldUsuario.getText());
                //pessoa.setSenha(jTextFieldSenha.getText());
                pessoa.setSexo((String) jComboBoxSexo.getSelectedItem());
        
        

                usuario.setUsuario(jTextFieldUsuario.getText());
                usuario.setSenha(jTextFieldSenha.getText());
                         
                         
                         
                         
                         
                         
                         
                         lp.alterarInformacao(indice, pessoa);
                         //System.out.println(pessoa);
                         lp.SalvaArquivoXML();
                         
                         preecherTabela();
               }
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
     
         
        
    }// Fecha chave alteraDados
    
    
    
    
    
    
    
    
    public void excluiDados(String nome) //Metodo para excluir um registro no XML
{
            
            int indice;
     try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("pessoa", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Pessoa> listaProf2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Pessoa pessoa: listaProf2)
              {
                  
               
               
                  if (nome.equals(pessoa.getNome()))
                  {
                      
                       
                         indice = listaProf2.indexOf(pessoa);
                         System.out.println(indice);
                         lp.removeProfessor(indice);
                      
                       
               }
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
    
}// chave exclui dados
    
    
    
    
    
    public  void preecherTabela() throws IOException //Metodo para inicializar a tabela com os dados dos registros do XML
    {
        
       //Estrutura da tabela
       ArrayList dados = new ArrayList();
       String [] Colunas = new String[]{"Nome", "RG", "CPF", "Endereco", "Cidade", "Numero", "Data de Nascimento", "Sexo", "Telefone", "Email", "Registro","Instituicao", "Usuario", "Senha"}; //Selecionando o nome das colunas
        
       ModeloTabela modelo = new ModeloTabela(dados, Colunas);
       jTableProfessor.setModel(modelo);
        
        
        
        //Buscando os dados do arquivo XML
        try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("pessoa", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Pessoa> listaProf2 = (ArrayList) xstream.fromXML(input);
              
              input.close();
         
              for(Pessoa pessoa: listaProf2)
              {
                  
                   dados.add(new Object[]{pessoa.getNome(), pessoa.getRG(), pessoa.getCPF(), pessoa.getEnd(), pessoa.getCidade(), pessoa.getNumero(), pessoa.getDate(), pessoa.getSexo(), pessoa.getTelefone(), pessoa.getEmail(), pessoa.getRegistro(),pessoa.getInstituicao(), pessoa.getUsuario(), pessoa.getSenha()});
                   
              }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//Metodo preencher tabela
    
    
    
    public void listaInstituicoes()
   {
       
      int indice;
     try {
             FileReader ler = new FileReader(diretorioInstituicao);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("instituicao", ArrayList.class);
              xstream.processAnnotations(Instituicao.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorioInstituicao));
              ArrayList<Instituicao> listaInstituicao2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Instituicao instituicao: listaInstituicao2)
              {
                  
               
               
                  jComboBoxInstituicao.addItem(instituicao.getNome());
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }  
    
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxInstituicao;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCab;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProfessor;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisar1;
    private javax.swing.JTextField jTextFieldRegistro;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
