/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import controle.ListaInstituicao;
import controle.ListaProfessores;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Instituicao;
import modelo.ModeloTabela;
import modelo.Pessoa;

/**
 *
 * @author Wellington
 */
public class ConfigInstituicao extends javax.swing.JFrame {
ListaInstituicao li = new ListaInstituicao();
String diretorio = "C:\\Users\\Wellington\\Documents\\FATEC\\Estrutura de Dados\\XMLs Projeto\\listaInstituicoes.xml";
String capturaNome;   
/**
     * Creates new form ConfigInstituicao
     */
    public ConfigInstituicao() {
        initComponents();
        
        bloqueiaCampos();
        desativaBtnEAS();
    li.recuperaDados();
        try { //Inicializa os valores do arquivo na tabela
            preecherTabela();
        } catch (IOException ex) {
            Logger.getLogger(ConfigProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    try {
        preecherTabela();
    } catch (IOException ex) {
        Logger.getLogger(ConfigInstituicao.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jComboBoxUf = new javax.swing.JComboBox();
        Estado = new javax.swing.JLabel();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldCnpj = new javax.swing.JFormattedTextField();
        Estado2 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        Estado1 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jPanelCab1 = new javax.swing.JPanel();
        jTextFieldPesquisar2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableInstituicao = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 640));
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(830, 590));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(860, 870));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Nome da Instituicao");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Endereço");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cidade");

        jComboBoxUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        Estado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Estado.setText("Estado");

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("CEP");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("CNPJ");

        try {
            jFormattedTextFieldCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Estado2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Estado2.setText("Email");

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        Estado1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Estado1.setText("Telefone");

        jPanelCab1.setBackground(new java.awt.Color(51, 51, 255));
        jPanelCab1.setPreferredSize(new java.awt.Dimension(834, 42));

        jTextFieldPesquisar2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldPesquisar2.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPesquisar2.setText("Pesquisar");
        jTextFieldPesquisar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPesquisar2MouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novo_projeto/imagens/Apesquisar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCab1Layout = new javax.swing.GroupLayout(jPanelCab1);
        jPanelCab1.setLayout(jPanelCab1Layout);
        jPanelCab1Layout.setHorizontalGroup(
            jPanelCab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCab1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jTextFieldPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanelCab1Layout.setVerticalGroup(
            jPanelCab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCab1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableInstituicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableInstituicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableInstituicao.setPreferredSize(new java.awt.Dimension(452, 402));
        jTableInstituicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableInstituicaoMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTableInstituicao);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldNome)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldEndereco)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCidade)
                    .addComponent(Estado)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(Estado2)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jTextFieldTelefone)
                    .addComponent(Estado1)
                    .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(219, 219, 219))
            .addComponent(jPanelCab1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addGap(97, 97, 97)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanelCab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(Estado2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Estado1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(Estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldPesquisar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPesquisar2MouseClicked
        // TODO add your handling code here:

        //jTextFieldPesquisar1.setText(" ");
    }//GEN-LAST:event_jTextFieldPesquisar2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        buscaDados(jTextFieldPesquisar2.getText());
        ativaBtnEAS();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTableInstituicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableInstituicaoMouseClicked
        // TODO add your handling code here:
        ativaBtnEAS();

        String nome = "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),0);
        String endereco= "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),1);
        String cidade= "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),2);
        String estado= "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),3);
        String cep= "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),4);
        String cnpj= "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),5);
        String email= "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),6);
        String telefone= "" + jTableInstituicao.getValueAt(jTableInstituicao.getSelectedRow(),7);
        

        jTextFieldNome.setText(nome);
        jTextFieldEndereco.setText(endereco);
        jTextFieldCidade.setText(cidade);
        jComboBoxUf.setSelectedItem(estado);
        jFormattedTextFieldCep.setText(cep);
        jFormattedTextFieldCnpj.setText(cnpj);
        jTextFieldEmail.setText(email);
        jTextFieldTelefone.setText(telefone);
        

       
    }//GEN-LAST:event_jTableInstituicaoMouseClicked

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
    CadInstituicao cadInst = new CadInstituicao(); 
    cadInst.setVisible(true);
    dispose();
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        
         String message = "Você tem certeza que deseja excluir este registro?";
        String title = "Excluir registro";

        int reply =  JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);

        if(reply == JOptionPane.YES_OPTION)
        {
            excluiDados(jTextFieldNome.getText());
            li.SalvaArquivoXML();
            try {
                preecherTabela();
            } catch (IOException ex) {
                Logger.getLogger(ConfigProfessor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }//chave da condição IF
        
        
        
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
         capturaNome = jTextFieldNome.getText();
        desbloqueiaCampos();
        jButtonSalvar.setVisible(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
         alteraDados(capturaNome);
        desativaBtnEAS();
        bloqueiaCampos();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    
    
    
     public void bloqueiaCampos()
    {
        
        
       jTextFieldNome.enable(false);
       jTextFieldEndereco.enable(false);
       jTextFieldCidade.enable(false);
       jFormattedTextFieldCep.enable(false);
       jFormattedTextFieldCnpj.enable(false);
       jTextFieldEmail.enable(false);
       jTextFieldTelefone.enable(false);
       jComboBoxUf.enable(false);
       
        
        
    }
    
    
    
    public void desbloqueiaCampos()
    {
        
      jTextFieldNome.enable(true);
       jTextFieldEndereco.enable(true);
       jTextFieldCidade.enable(true);
       jFormattedTextFieldCep.enable(true);
       jFormattedTextFieldCnpj.enable(true);
       jTextFieldEmail.enable(true);
       jTextFieldTelefone.enable(true);                                       
       jComboBoxUf.enable(true); 
    }
    
    
    
 
    public void ativaBtnEAS()
    {
        
        jButtonExcluir.setVisible(true);
        jButtonAlterar.setVisible(true);
       // jButtonSalvar.setVisible(true);
        
    }
    
    
    public void desativaBtnEAS()
    {
        
        jButtonExcluir.setVisible(false);
        jButtonAlterar.setVisible(false);
        jButtonSalvar.setVisible(false);
        
    }
    
    
     public void buscaDados(String nome)
    {
        
        
        int indice;
     try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("instituicao", ArrayList.class);
              xstream.processAnnotations(Instituicao.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Instituicao> listaInstituicao2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Instituicao instituicao: listaInstituicao2)
              {
                  
               
               
                  if (nome.equals(instituicao.getNome()))
                  {
                      
                        jTextFieldNome.setText(instituicao.getNome());
                        jTextFieldEndereco.setText(instituicao.getEndereco());
                        jTextFieldCidade.setText(instituicao.getCidade());
                        jComboBoxUf.setSelectedItem(instituicao.getEstado());
                        jFormattedTextFieldCep.setText(instituicao.getCEP());
                        jFormattedTextFieldCnpj.setText(instituicao.getCNPJ());
                        jTextFieldEmail.setText(instituicao.getEmail());
                        jTextFieldTelefone.setText(instituicao.getTelefone());
                      
                       
               }
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    public void alteraDados(String nome)
    {
      int indice;  
       try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("instituicao", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Instituicao> listaInstituicao2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Instituicao instituicao: listaInstituicao2)
              {
                  
               
               
                  if (nome.equals(instituicao.getNome()))
                  {
                      
                       
                         indice = listaInstituicao2.indexOf(instituicao);
                         System.out.println(indice);
                         
                        
                         
                           
                    // Passando dados para a a classe pessoa
                    instituicao.setNome(jTextFieldNome.getText());
                    instituicao.setEndereco(jTextFieldEndereco.getText());
                    instituicao.setCidade(jTextFieldCidade.getText());
                    instituicao.setEstado((String) jComboBoxUf.getSelectedItem());
                    instituicao.setCEP(jFormattedTextFieldCep.getText());
                    instituicao.setCNPJ(jFormattedTextFieldCnpj.getText());
                    instituicao.setEmail(jTextFieldEmail.getText());
                    instituicao.setTelefone(jTextFieldTelefone.getText());
                         
                         
                         
                         
                         
                         
                         li.alterarInformacao(indice, instituicao);
                         //System.out.println(pessoa);
                         li.SalvaArquivoXML();
                         
                         preecherTabela();
               }
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
     
         
        
    }// Fecha chave alteraDados
    
    
    
    
    
    
    
    
    public void excluiDados(String nome) //Metodo para excluir um registro no XML
{
            
            int indice;
     try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("instituicao", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Instituicao> listaInstituicao2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Instituicao instituicao: listaInstituicao2)
              {
                  
               
               
                  if (nome.equals(instituicao.getNome()))
                  {
                      
                       
                         indice = listaInstituicao2.indexOf(instituicao);
                         System.out.println(indice);
                         li.removeInstituicao(indice);
                      
                       
               }
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
    
}// chave exclui dados
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     public  void preecherTabela() throws IOException //Metodo para inicializar a tabela com os dados dos registros do XML
    {
        
       //Estrutura da tabela
       ArrayList dados = new ArrayList();
       String [] Colunas = new String[]{"Nome", "Endereco", "Cidade", "UF", "CEP", "CNPJ", "Email", "Telefone"}; //Selecionando o nome das colunas
        
       ModeloTabela modelo = new ModeloTabela(dados, Colunas);
       jTableInstituicao.setModel(modelo);
        
        
        
        //Buscando os dados do arquivo XML
        try {
             FileReader ler = new FileReader(diretorio);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("instituicao", ArrayList.class);
              xstream.processAnnotations(Instituicao.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorio));
              ArrayList<Instituicao> listaInstituicao2 = (ArrayList) xstream.fromXML(input);
              
              input.close();
         
              for(Instituicao instituicao: listaInstituicao2)
              {
                  
                   dados.add(new Object[]{instituicao.getNome(), instituicao.getEndereco(), instituicao.getCidade(), instituicao.getEstado(), instituicao.getCEP(), instituicao.getCNPJ(), instituicao.getEmail(), instituicao.getTelefone()});
                   
              }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//Metodo preencher tabela
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigInstituicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Estado1;
    private javax.swing.JLabel Estado2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxUf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnpj;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCab1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableInstituicao;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar2;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
