/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import controle.ListaProfessores;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import visao.VisaoAdmin.MainAdm;
import javax.swing.JOptionPane;
import modelo.Pessoa;
import modelo.Usuario;

/**
 *
 * @author Wellington
 */
public class Login extends javax.swing.JFrame {
String diretorioProfessor = "C:\\Users\\Wellington\\Documents\\FATEC\\Estrutura de Dados\\XMLs Projeto\\listaProfessores.xml"; //Diretorio do XML professores
String diretorioAluno = "C:\\Users\\Wellington\\Documents\\FATEC\\Estrutura de Dados\\XMLs Projeto\\listaAlunos.xml";

    String usuario,senha,tipo;
   private String nomeUsuarioLogado;
   private String teste;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        jLabelLogin.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonLogar = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 110, -1));

        jButtonLogar.setText("Entrar");
        jButtonLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 0, 0));
        jLabelLogin.setText("Usuário ou senha esta incorreto, tente novamente");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/login.png"))); // NOI18N
        jLabelFundo.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, -180, 1960, 1030));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarActionPerformed
        // TODO add your handling code here:
           
        buscaDadosProfessor(jTextFieldLogin.getText(), jPasswordField.getText());
        buscaDadosAluno(jTextFieldLogin.getText(), jPasswordField.getText());
         
        
        /*MainAdm adm = new MainAdm();
        PrincipalAluno pAluno = new PrincipalAluno();
        if(jTextFieldLogin.getText().equals("admin") && jPasswordField.getText().equals("1234"))
        {
                
                 adm.setMaximumSize(null);
                adm.setVisible(true);
        
        dispose();
        }
        
        else if(jTextFieldLogin.getText().equals("aluno") && jPasswordField.getText().equals("aluno"))
        {
                
                 pAluno.setMaximumSize(null);
                pAluno.setVisible(true);
        
        dispose();
        }
        
        
        
        
        else
        {
            JOptionPane.showMessageDialog(null, "Login ou Senha incorretos, tente novamente");
        }*/
        
    }//GEN-LAST:event_jButtonLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    public void buscaDadosAluno(String login, String senha)
    {
        
        
        int indice;
     try {
             FileReader ler = new FileReader(diretorioAluno);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("pessoa", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorioAluno));
              ArrayList<Pessoa> listaAluno2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Pessoa pessoa: listaAluno2)
              {
                  
                
               
                   if (login.equals(pessoa.getUsuario())&& jPasswordField.getText().equals(pessoa.getSenha())&&pessoa.getTipousuario().equals("Aluno"))
                  {
                      PrincipalAluno pAluno = new PrincipalAluno();
                      pAluno.setVisible(true);
                      
                     
                     
                      
                      
                      dispose();
                      
                      
                      
                  }
                  
                 else
                  {
                      jLabelLogin.setVisible(true);
                  }
                  
                  
                  
                   
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
        
       
    }
    
    

    
    
    
    
  
    
     public void buscaDadosProfessor(String login, String senha)
 {
     int indice;
     try {
             FileReader ler = new FileReader(diretorioProfessor);
              XStream xstream = new XStream(new DomDriver());
              xstream.alias("pessoa", ArrayList.class);
              xstream.processAnnotations(Pessoa.class);
              
              BufferedReader input = new BufferedReader(new FileReader(diretorioProfessor));
              ArrayList<Pessoa> listaProf2 = (ArrayList) xstream.fromXML(input);
              input.close();
              
              
              for(Pessoa pessoa: listaProf2)
              {
                  
               
               
                  if (login.equals(pessoa.getUsuario())&& jPasswordField.getText().equals(pessoa.getSenha())&& pessoa.getTipousuario().equals("Professor"))
                  {
                      PrincipalProfessor pProf = new PrincipalProfessor();
                      pProf.setVisible(true);
                      
                      dispose();  
                      
               }
                  
                 else
                  {
                      jLabelLogin.setVisible(true);
                  }
                      
            }
              
              
         
         } catch (FileNotFoundException ex) {
             Logger.getLogger(ListaProfessores.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
         
             
             Logger.getLogger(CadProfessor.class.getName()).log(Level.SEVERE, null, ex);
     }
            
 }// chave buscaDados
    
 
    public void setUsuarioLogado(String ul)
    {
            
        nomeUsuarioLogado  = ul;
    }
    
    public String getUsuarioLogado()
            {
                return nomeUsuarioLogado;
            }

    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
